language: python
python:
  - "2.7"
install:
  - pip install -r requirements/testing.txt
  - pip install coveralls
env:
  - DJANGO_SETTINGS_MODULE=config.settings.dev
before_script:
  - cd paying-for-college
  # - python manage.py makemigrations
  # - python manage.py migrate
script: 
  # - nosetests --with-coverage --config=.coveragerc --cover-package disclosures
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
